# This is a basic workflow to help you get started with Actions

name: GerenciarAluno


on:
  push:
    branches: [ master ]
jobs:
   build:
    
    runs-on: self-hosted

    
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
      - run: echo Sera que da certo?
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        
        

    
    
